import {useEffect,useState} from 'react';
import {ApiError,errorText,rpc,type Master} from './api';
import {today} from './gantt-model';
import './inventory.css';
type Row={ordinal:number;lot:string;sourceSheet:string;sourceRow:number;plantingYear:number|null;area:number|string|null;areaAlqueria:number|null;trees:number|null;productionTrees:number|null;alive:number|null;dead:number|null;replanted:number|null;totalAlive:number|null;issues:string[];state:string;rawValues:unknown[];formulas:Record<string,string>;masterMatch:boolean};
type Version={id:string;fileName:string;fileHash:string;createdAt:string;effectiveDate:string|null;confirmationNote:string|null;periodLabel:string;summary:{rows:number;review:number};warnings:string[];includedTotals:{area:number|null;areaAlqueria:number|null;totalAlive:number|null;planted:number|null}};
type Result={version:Version|null;versions:Version[];rows:Row[];total:number;comparison:{previousDate:string;added:number;removed:number}|null};
const value=(v:number|string|null|undefined)=>v===null||v===undefined?'—':typeof v==='number'?v.toLocaleString('es-CO',{maximumFractionDigits:3}):v;
const labels:Record<string,string>={area:'Área principal (Ha)',areaAlqueria:'Área Alquería (Ha)',totalAlive:'Total de plantas vivas',planted:'Plantación sembrada'};
export function Inventory({master,onDenied,onLot}:{master:Master;onDenied:()=>void;onLot:(lot:string)=>void}){
 const [mode,setMode]=useState('version'),[versionId,setVersionId]=useState(''),[asOf,setAsOf]=useState(''),[search,setSearch]=useState(''),[review,setReview]=useState(false),[offset,setOffset]=useState(0),[attempt,setAttempt]=useState(0);
 const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null);
 const [effective,setEffective]=useState(''),[note,setNote]=useState(''),[ack,setAck]=useState(false);
 useEffect(()=>{const abort=new AbortController();setResult(null);setError('');setSelected(null);
  if(mode==='date'&&!asOf){setError('Selecciona una fecha para consultar solo versiones confirmadas.');return}
  void rpc<Result>('web5_inventory',{p_version:mode==='version'?(versionId||null):null,p_as_of:mode==='date'?asOf:null,p_search:search||null,p_state:review?'REVIEW':null,p_offset:offset},abort.signal).then(data=>{if(!abort.signal.aborted)setResult(data)}).catch(e=>{
   if(abort.signal.aborted)return;if(e instanceof ApiError&&e.code==='ACCESS_DENIED')onDenied();else setError(errorText(e));
  });return()=>abort.abort();
 },[mode,versionId,asOf,search,review,offset,attempt,master.snapshotHash,onDenied]);
 useEffect(()=>{setEffective('');setNote('');setAck(false)},[versionId,mode,asOf]);
 async function confirm(){
  if(!result?.version||busy||!ack||!effective||note.trim().length<10)return;
  if(!window.confirm('¿Confirmas esta fecha efectiva y aceptas las observaciones del Excel? La versión quedará inmutable. Esto no corrige las cifras originales.'))return;
  setBusy(true);setError('');try{await rpc('web5_confirm_inventory',{p_version:result.version.id,p_effective:effective,p_note:note,p_acknowledge:ack});setAttempt(n=>n+1)}catch(e){if(e instanceof ApiError&&e.code==='ACCESS_DENIED')onDenied();else setError(errorText(e))}finally{setBusy(false)}
 }
 const version=result?.version;
 return <div className="stack"><section className="panel inventory-panel"><span className="eyebrow">Maestro secundario · independiente de labores</span><h2>Inventario general</h2><p className="muted">Versiones consultables del Excel. No se editan existencias ni se recalculan fórmulas desde esta web. El método de futuras actualizaciones aún debe definirse.</p>
  <div className="filters"><label>Consultar por<select value={mode} onChange={e=>{setMode(e.target.value);setOffset(0)}}><option value="version">Versión cargada</option><option value="date">Fecha histórica</option></select></label>
   {mode==='version'?<label>Versión<select value={versionId} onChange={e=>{setVersionId(e.target.value);setOffset(0)}}><option value="">Última cargada (puede estar pendiente)</option>{result?.versions.map(v=><option key={v.id} value={v.id}>{v.effectiveDate??'Fecha pendiente'} · {v.fileName} · {v.id.slice(0,8)}</option>)}</select></label>:<label>Vigente a fecha<input type="date" value={asOf} onChange={e=>{setAsOf(e.target.value);setOffset(0)}}/></label>}
   <label>Buscar lote<input type="search" value={search} maxLength={250} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></label><label>Validación<select value={review?'REVIEW':''} onChange={e=>{setReview(Boolean(e.target.value));setOffset(0)}}><option value="">Todas las filas</option><option value="REVIEW">Con pendientes</option></select></label><button className="secondary" onClick={()=>setAttempt(n=>n+1)}>Actualizar consulta</button>
  </div>{error&&<p role="alert" className="notice error">{error}</p>}{!result&&!error&&<p role="status">Consultando inventario privado…</p>}
  {result&&!version&&<p className="notice">{mode==='date'?'No hay una versión confirmada con vigencia en esta fecha. No se utilizará una posterior.':'Todavía no se ha preparado una versión de inventario.'}</p>}
  {version&&<><div className="notice" role="status">{version.effectiveDate?`Versión confirmada con fecha efectiva ${version.effectiveDate}. Consulta informativa: no se aplica automáticamente al avance del Gantt.`:'VISTA PREVIA — Fecha efectiva pendiente. No es inventario vigente y no se utilizará en cálculos históricos.'}</div>
   <p><strong>Referencia del archivo:</strong> {version.periodLabel}</p><p className="muted">Solo se incluyen filas con lote y año de siembra. Los totales suman exclusivamente esas filas.</p><div className="metrics">{[['Filas incluidas',version.summary.rows],['Filas con pendientes',version.summary.review],['Plantas vivas incluidas',version.includedTotals?.totalAlive],['Árboles sembrados incluidos',version.includedTotals?.planted]].map(([label,n])=><article className="metric" key={label}><span>{label}</span><strong>{value(n)}</strong><small>Filas incluidas · valores guardados en Excel</small></article>)}</div>
   {version.warnings.filter(w=>!version.effectiveDate||!w.startsWith('Fecha efectiva')).map(w=><p className="notice" key={w}>{w.replace('de planted','de plantación sembrada')}</p>)}
   <details><summary>Totales incluidos y procedencia</summary><div className="table-wrap"><table><thead><tr><th>Concepto</th><th>Suma de filas incluidas</th></tr></thead><tbody>{Object.entries(version.includedTotals??{}).map(([field,n])=><tr key={field}><td>{labels[field]??field}</td><td>{value(n)}</td></tr>)}</tbody></table></div><p className="muted">Los vacíos y textos no aportan a la suma; esto no significa que valgan cero. No se usan los totales generales del archivo, pues pueden incluir filas omitidas. Archivo: {version.fileName}. Huella: <code>{version.fileHash}</code>.</p></details>
   {result.comparison?<p className="notice">Frente a la versión efectiva del {result.comparison.previousDate}: {result.comparison.added} contenidos nuevos y {result.comparison.removed} que dejaron de aparecer. Una corrección puede figurar en ambas cifras; no se infiere identidad de filas.</p>:<p className="muted">Sin versión anterior confirmada para comparar.</p>}
   <div className="table-wrap"><table><caption>Inventario por lote · valores originales</caption><thead><tr><th>Lote / año</th><th>Área (Ha)</th><th>Área Alquería</th><th>Árboles</th><th>Producción 2024/2025</th><th>Vivos</th><th>Muertos</th><th>Resiembra</th><th>Total vivas</th><th>Detalle</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.ordinal}><td><strong>{r.lot}</strong><small>{r.plantingYear??'—'}</small>{r.masterMatch?<button className="text-button" onClick={()=>onLot(r.lot)}>Ver labores (coincidencia literal)</button>:<small>Sin asociación inequívoca</small>}</td>{[r.area,r.areaAlqueria,r.trees,r.productionTrees,r.alive,r.dead,r.replanted,r.totalAlive].map((v,i)=><td key={i}>{value(v)}</td>)}<td><span className={`state ${r.state==='REVIEW'?'state-observed':'state-valid'}`}>{r.state==='REVIEW'?'Revisar':'Sin hallazgos de fila'}</span><button className="text-button" onClick={()=>setSelected(r)}>{r.sourceSheet} · fila {r.sourceRow}</button></td></tr>)}</tbody></table></div>
   <div className="pagination"><span>{result.total?`${offset+1}–${Math.min(result.total,offset+25)} de ${result.total}`:'Sin coincidencias'}</span><div><button className="secondary" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-25))}>Anterior</button><button className="secondary" disabled={offset+25>=result.total} onClick={()=>setOffset(n=>n+25)}>Siguiente</button></div></div>
   {selected&&<section className="notice" aria-label="Detalle de inventario"><h3>{selected.lot} · {selected.sourceSheet}, fila {selected.sourceRow}</h3>{selected.issues.length?selected.issues.map(issue=><p key={issue}>{issue}</p>):<p>Sin hallazgos locales; revisa también las observaciones generales.</p>}<details><summary>Valores originales y fórmulas guardadas</summary><pre className="inventory-raw">{JSON.stringify({values:selected.rawValues,formulaXml:selected.formulas},null,2)}</pre><p>Fórmulas compartidas conservan su referencia Excel. No se ejecutan en la web.</p></details><button className="text-button" onClick={()=>setSelected(null)}>Cerrar detalle</button></section>}
   {!version.effectiveDate?<details className="inventory-confirm"><summary>Confirmar esta versión después de revisar el Excel</summary><p>La fecha debe ser la del inventario, no la fecha de carga. Se conservarán los datos y las observaciones. No se modifica el archivo original.</p><form onSubmit={e=>{e.preventDefault();void confirm()}}><div className="filters"><label>Fecha efectiva confirmada<input required type="date" min="1900-01-01" max={today()} value={effective} onChange={e=>setEffective(e.target.value)}/></label><label>Nota de validación<input required minLength={10} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Quién confirmó la fecha y las observaciones"/></label></div><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> Revisé las filas incluidas y sus pendientes; confirmo esta fecha.</label><p><button className="primary" disabled={busy||!ack||!effective||note.trim().length<10}>{busy?'Confirmando…':'Confirmar versión'}</button></p></form></details>:<p className="muted">Nota de confirmación: {version.confirmationNote}. Esta versión no puede sobrescribirse.</p>}
  </>}
 </section></div>;
}
